# Generated by Django 4.2.4 on 2023-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_Name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='app1.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
