# Generated by Django 4.2.4 on 2023-10-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_student_teacher_remove_student_student_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
