# Generated by Django 4.2.4 on 2023-10-18 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_student_students_rename_teacher_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('TeacherID', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=50)),
                ('Teacher_Name', models.CharField(max_length=50)),
                ('Issued_Date', models.DateField(default=datetime.date.today)),
                ('JWT_Token', models.TextField()),
            ],
        ),
    ]
